/// Flutter icons RpgIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RpgIcons
///      fonts:
///       - asset: fonts/RpgIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RpgIcons {
  RpgIcons._();

  static const _kFontFam = 'RpgIcons';

  static const IconData bow_arrow = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dragon_head = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData dwarf_face = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData hooded_figure = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData rope_coil = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData spell_book = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData standing_potion = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData swap_bag = const IconData(0xe808, fontFamily: _kFontFam);

  static IconData getIconDataByName(String name){
    switch(name){
      case 'weapons':
        return bow_arrow;
      case 'monsters':
        return dragon_head;
      case 'races':
        return dwarf_face;
      case 'classes':
        return hooded_figure;
      case 'adventuring-gear':
        return rope_coil;
      case 'armor':
        return shield;
      case 'spells':
        return spell_book;
      case 'potions':
        return standing_potion;
      case 'items':
        return swap_bag;
      case 'misc-items':
        return swap_bag;
      default:
        return shield;
    }
  }
}
